server:
  port: ${PORT}

lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: false  # disable old extractor
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 400
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    resamplingQuality: HIGH

plugins:
  youtube:
    enabled: true  # enable new youtube-source plugin

logging:
  file:
    path: ./logs/
  level:
    root: INFO
    lavalink: INFO
