server:
  port: ${PORT}

lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: false  # disable old extractor
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 400
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    resamplingQuality: HIGH

plugins:
  youtube:
    enabled: true
  lavasrc:
    enabled: true
    providers:
      - "spotify"
      - "deezer"
      - "applemusic"
    spotify:
      clientId: "55216b256f2e4beca298bfe20d961052"
      clientSecret: "fd5a28401084454497afefc48d2f7c26"


logging:
  file:
    path: ./logs/
  level:
    root: INFO
    lavalink: INFO
