server:
  port: ${PORT}  # Render automatically assigns a port, this keeps it dynamic

lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: false  # Disable old built-in extractor (we use the plugin instead)
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 400
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    resamplingQuality: HIGH

plugins:
  youtube:
    enabled: true
    clients:
      - WEB
      - WEB_REMIX
      - ANDROID_VR
      - WEB_EMBEDDED_PLAYER

  lavasrc:
    enabled: true
    providers:
      - "spotify"
      - "deezer"
      - "applemusic"
    spotify:
      clientId: "55216b256f2e4beca298bfe20d961052"
      clientSecret: "fd5a28401084454497afefc48d2f7c26"
    deezer:
      masterDecryptionKey: "e82ckOhfWiF8HqZ7KchW0FzghkFzBP5eb9xvQLuK7y0="

logging:
  file:
    path: ./logs/
  level:
    root: INFO
    lavalink: INFO
